### PR TITLE
Origin/invalid date format

### PR DESCRIPTION
**Pull request by witcher-the**

### CODE REVIEW

**Comment by witcher-the** [comment]
@kekeh would you be so nice and check if the changes in this PR are ok?

**Comment by kekeh** [comment]
This PR breaks the example application.

screenshot_2017-12-06_14-42-29

Can you check and fix it asap?

Start example application: **npm start**
Open to browser: **http://localhost:5000**

check console of the browser.

**Comment by kekeh** [comment]
I already fixed it. You don't need to check it.

**Comment by kekeh** [comment]
I merged this PR. New version of the component is 2.3.4.

**Pull request merged**
